#!/bin/bash

#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "${__CUSTOM_CONSOLE_UTIL}"/__common

function __contexts_header() {

	local msg="todo.sh | enter: traverse context task(s) | ?: toggle preview | esc: quit"
	local colorMsgL1="${UNDERLINE}${MAGENTA}todo.sh${RESET} | \
${BLUE}enter:${RESET} traverse context task(s) | \
${BLUE}?:${RESET} toggle preview | \
${BLUE}esc:${RESET} quit"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local contextsHeader="${edge}"'
'"${colorMsgL1}"'
'"${edge}"'
 '

	echo "${contextsHeader}"
}