#!/bin/bash

source "${__CUSTOM_CONSOLE_UTIL}"/__common
source "${__CUSTOM_CONSOLE_UTIL}"/__println_as

function __project_wise_tasks_preview() {

	local project="${1}"
	__println_as "cyan" "bold" "Project: ${project}"
	echo
	todo.sh ls "+${project}" | grep -v TODO | grep -v "\-\-" | sort
}
