#!/bin/bash

#shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.

source "${__CUSTOM_CONSOLE_UTIL}"/__common
source "${__CUSTOM_CONSOLE_UTIL}"/__print_as
source "${__CUSTOM_CONSOLE_UTIL}"/__println_as
source "${__CUSTOM_CONSOLE_UTIL}"/urls/__fetch_urls

function __url_preview() {

	echo

	local urlAlias="${1}"
	local url="$(__fetch_urls | grep "${urlAlias}" | awk '{split($0,a,":::"); print a[2]}' | xargs -I {} echo {})"
	__print_as "bold" "URL: "
	__println_as "blue" "${url}"
}

# References:
# cut: https://shapeshed.com/unix-cut/#:~:text=To%20cut%20using%20a%20delimiter,field%20that%20should%20be%20cut.