#!/bin/bash

# Usage: __apply_tput "red"
function __apply_tput() {

    case "${1}" in
        black) tput setaf 0
        ;;
        red) tput setaf 1
        ;;
        green) tput setaf 2
        ;;
        yellow) tput setaf 3
        ;;
        blue) tput setaf 4
        ;;
        magenta) tput setaf 5
        ;;
        cyan) tput setaf 6
        ;;
        white) tput setaf 7
        ;;
        reset) tput sgr0
        ;;
        *) tput "${1}"
        ;;
    esac
}