#!/bin/bash

#shellcheck disable=SC2155
#shellcheck disable=SC2034	#	SUCCESS appears unused. Verify use (or export if used externally)

export BLACK="$(tput setaf 0)"
export RED="$(tput setaf 1)"
export GREEN="$(tput setaf 2)"
export YELLOW="$(tput setaf 3)"
export BLUE="$(tput setaf 4)"
export MAGENTA="$(tput setaf 5)"
export CYAN="$(tput setaf 6)"
export WHITE="$(tput setaf 7)"
export BOLD="$(tput bold)"
export UNDERLINE="$(tput smul)"
export REVERSE="$(tput rev)"
export RESET="$(tput sgr0)"

SUCCESS=0
FAILURE=1