#!/bin/bash

#shellcheck disable=SC1091

			#   $0       $1    $2      $3
# Usage: __print_as "bold" "red" "Some text"
function __print_as() {

	source "${__CUSTOM_CONSOLE_UTIL}"/__apply_tput

	while [[ $# -gt 1 ]]; do
		__apply_tput "${1}"
		shift
	done

	local msg="${1}"
	printf "%s" "${msg}"

	__apply_tput reset
}