#!/bin/bash

# Usage : __split_str "str" "substr"
# str : input string
# substr : delimiter substring
# Output: RESULT_ARR
function __split_str() {
	local str="${1}"
	local delim="${2}"
	local suffix=""

	RESULT_ARR=()
	while [[ "${str}" != "${suffix}" ]]; do
		suffix=${str/*$delim/}			# remove prefix
		str=${str%"$delim$suffix"}		# remove suffix
		RESULT_ARR=("$suffix" "${RESULT_ARR[@]}")    # prepend to the result array
	done
}
