#!/bin/bash

#shellcheck disable=SC2155
#shellcheck disable=SC1091

source "$__CUSTOM_CONSOLE_UTIL"/__split_str
source "$__CUSTOM_CONSOLE_UTIL"/__url_encode

# Usage: __split_into_encoded_arr_by_arrow "${input_str}"
# Output: RESULT_ARR
function __split_into_encoded_arr_by_arrow() {
	
	local str="${1}"
	local encodedStr="$(__url_encode "${str}")"
	local encodedArrow="$(__url_encode " -> ")"

	__split_str "${encodedStr}" "${encodedArrow}"
}