#!/bin/bash

# shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.

source "${__CUSTOM_CONSOLE_UTIL}"/urls/__fetch_urls

function __open_urls() {

	local urlAlias="${1}"
	__fetch_urls | grep "${urlAlias}" | cut -d ' ' -f 2 | xargs -I {} open {}
}