#!/bin/bash

# shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.

source "${__CUSTOM_CONSOLE_UTIL}"/urls/__fetch_urls

function __open_url() {

	local urlAlias="${1}"
	local url="$(__fetch_urls | grep "${urlAlias}" | awk '{split($0,a,":::"); print a[2]}' | xargs -I {} echo {})"
	open "${url}"
}