#!/bin/bash

# shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.

source "${__CUSTOM_CONSOLE_UTIL}"/urls/__read_urls_file

URLS_FILE_PATH="${__CUSTOM_CONSOLE_UTIL}/urls/urls.txt"

function __remove_urls() {

	local urlAlias="${1}"
	__read_urls_file | grep -v "${urlAlias}" "${URLS_FILE_PATH}" > temp && mv temp "${URLS_FILE_PATH}"
}