#!/bin/bash

# shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.

source "${__CUSTOM_CONSOLE_UTIL}"/urls/__read_urls_file

function __view_urls() {

	local urlAlias="${1}"
	__read_urls_file | grep "${urlAlias}" | cut -d ' ' -f 2 | xargs -I {} echo {}
}