#!/bin/bash

#shellcheck disable=SC2155
#shellcheck disable=SC1091

#source "$__CUSTOM_GIT_UTIL"/fzf_preview/__gshow_preview
#source "$__CUSTOM_GIT_UTIL"/fzf_header/__glog_header

function main() {

  while true; do
    local selectedStr="$(todo.sh lsprj | fzf --preview "todo.sh ls {}")"
		if [[ -z "${selectedStr}" ]]; then
			break
		fi
    todo.sh ls "${selectedStr}" |\
      fzf --bind "ctrl-u:execute-silent(source $__CUSTOM_CONSOLE_UTIL/fzf_action/tl/__prioritize_up; __prioritize_up {})" \
          --bind "ctrl-u:+reload(todo.sh ls ${selectedStr})" \
          --bind "ctrl-d:execute-silent(source $__CUSTOM_CONSOLE_UTIL/fzf_action/tl/__prioritize_down; __prioritize_down {})" \
          --bind "ctrl-d:+reload(todo.sh ls ${selectedStr})"
  done

#	local GLOG_HEADER="$(__glog_header)"
#
#	while true; do
#		local selectedStr="$(git log --pretty='format:%C(auto)%h%d [%an] [%ar] %s' --graph --color=always |\
#			fzf --bind "q:abort"\
#				--bind "?:toggle-preview"\
#				--bind "ctrl-c:preview(source $__CUSTOM_GIT_UTIL/fzf_actions/__gshow_actions; __gshow_actions {})"\
#				--header "${GLOG_HEADER}"\
#				--preview-window hidden\
#				--preview "source $__CUSTOM_GIT_UTIL/fzf_previews/__gshow_preview; __gshow_preview {}")"
#
#		if [[ -z "${selectedStr}" ]]; then
#			break
#		fi
#		__gshow_preview "${selectedStr}"
#	done
}

main