#!/bin/bash

#shellcheck disable=SC2155

source "$__CUSTOM_CONSOLE_UTIL"/fzf_header/tl/__projects_header

function main() {

  while true; do

		local PROJECT_HEADER="$(__projects_header)"

    local selectedStr="$(todo.sh lsprj | sed -e s/.// | \
                          fzf --header "${PROJECT_HEADER}" \
                              --preview "source $__CUSTOM_CONSOLE_UTIL/fzf_preview/tl/__tasks_preview; __tasks_preview {}" \
                              --preview-window hidden \
                              --preview-window nowrap \
                              --bind "?:toggle-preview" \
                              --bind "ctrl-w:toggle-preview-wrap")"
		if [[ -z "${selectedStr}" ]]; then
			break
		fi

    todo.sh ls "+${selectedStr}" | grep -v TODO | grep -v "\-\-" | \
      fzf --bind "ctrl-j:execute-silent(source $__CUSTOM_CONSOLE_UTIL/fzf_action/tl/__prioritize_up; __prioritize_up {})" \
          --bind "ctrl-j:+reload(todo.sh ls ${selectedStr})" \
          --bind "ctrl-k:execute-silent(source $__CUSTOM_CONSOLE_UTIL/fzf_action/tl/__prioritize_down; __prioritize_down {})" \
          --bind "ctrl-k:+reload(todo.sh ls ${selectedStr})" \
          --bind "ctrl-d:execute-silent(source $__CUSTOM_CONSOLE_UTIL/fzf_action/tl/__mark_done; __mark_done {})" \
          --bind "ctrl-d:+reload(todo.sh ls ${selectedStr})" \
          --bind "ctrl-r:execute-silent(source $__CUSTOM_CONSOLE_UTIL/fzf_action/tl/__remove_todo; __remove_todo {})" \
          --bind "ctrl-r:+reload(todo.sh ls ${selectedStr})"
  done
}

main