#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __new_url_header() {

    local colorMsg="Enter the new URL\n\n"
    colorMsg="${colorMsg}${BLUE}esc:${RESET} go back"

    local edge="--------------------------------------------------------------------------"
    local newUrlHeader="${edge}\n${colorMsg}\n "

    echo -e "${newUrlHeader}"
}