#!/bin/bash

#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "${__CUSTOM_CONSOLE_UTIL}"/__common

function __urls_header() {

	local msg="urls | enter: open url in web browser | ?: toggle preview | esc: quit"
	local colorMsgL1="${UNDERLINE}${MAGENTA}url${RESET} | \
${BLUE}enter:${RESET} open url in web browser | \
${BLUE}?:${RESET} toggle preview | \
${BLUE}esc:${RESET} quit"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local urlsHeader="${edge}"'
'"${colorMsgL1}"'
'"${edge}"'
 '

	echo "${urlsHeader}"
}